### PR TITLE
Don't use the default ExecutionContext

### PR DESCRIPTION
**Pull request by rjmac**
We actually want parallelism, and with the Ubuntu upgrade, the EC
now believes that the CPU count (and hence the threads it's willing
to create) is 1.

### CODE REVIEW

**Comment by znep** [comment]
Hrm, surprised we need to make our own `BlockingThreadPool` to do this and there isn't just an existing executor we can plug in, but you know better than I do there and I didn't really read what is going on.

Can we also expose this setting as an env variable in the docker config it can override?  I have a hunch I may want to be tweaking it.

**Comment by rjmac** [comment]
There probably is one in a library somewhere, but the closest thing to it in the stdlib is the fixed-size thread pool, as far as I know (and off the top of my head, I'm not sure if that blocks or rejects when the pool is full)

**Comment by znep** [comment]
Looks like the default uses ForkJoinPool https://github.com/scala/scala/blob/v2.10.7/src/library/scala/concurrent/impl/ExecutionContextImpl.scala#L77-L81

**Comment by rjmac** [comment]
Oh hey you're right.  That has the behavior we want.  I'll switch.

**Comment by chitang** [comment]
:shipit:

**Pull request merged**
