### PR TITLE
Require feature primary key as a parameter in region-coding requests

### PR DESCRIPTION
**Pull request by urmilan**

### CODE REVIEW

**Comment by urmilan** [comment]
Needs a couple extra things, pls dont merge yet

**Comment by urmilan** [comment]
I ended up doing the extra work in another spot, feel free to review/merge

**Comment by kaidamasaki** [comment]
The current pieces look good to me.  Though, it looks like there's no multiple region v2 testing.

**Comment by urmilan** [comment]
Thanks for the catch @kaidamasaki - I added the extra test that you suggested. Gonna merge now.

**Pull request merged**
